# Generated by Django 5.1.6 on 2025-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0045_smileycategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_games',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loisirs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.AddField(
            model_name='profile',
            name='aim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chinese_sign',
            field=models.CharField(blank=True, choices=[('rat', '鼠 Rat'), ('buffle', '牛 Buffle'), ('tigre', '虎 Tigre'), ('lapin', '兔 Lapin'), ('dragon', '龙 Dragon'), ('serpent', '蛇 Serpent'), ('cheval', '马 Cheval'), ('chevre', '羊 Chèvre'), ('singe', '猴 Singe'), ('coq', '鸡 Coq'), ('chien', '狗 Chien'), ('cochon', '猪 Cochon'), ('', 'Aucun')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='icq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jabber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='msnm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='yim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
